CR 		EQU 	0DH
LF 		EQU 	0AH

DATA 		SEGMENT
TABLE 		DB 	'0123456789'
LSBDIVIDENT 	DB 	09
MSBDIVIDENT 	DB 	00
DIVISOR 		DB 	09
MESSAGE1 	DB 	' THE QUOTIENT IS '
ASCIIQUOTIENT 	DB 	1 dup(?)
 		DB 	CR, LF, '$'
MESSAGE2 	DB 	' THE REMAINDER IS '
ASCIIREMAINDER 	DB 	1 dup(?)
		DB 	CR, LF, '$'

DATA 		ENDS

CODE 		SEGMENT
		Assume 	CS:Code, DS: Data
START: 		MOV 	AX, DATA
 		MOV 	DS, AX
 		MOV 	AL, LSBDIVIDENT
		MOV 	AH, MSBDIVIDENT
		MOV 	DH,DIVISOR
 		DIV 	DH
 		LEA 	BX,TABLE
		LEA 	SI, ASCIIQUOTIENT
 		XLAT
 		MOV 	[SI], AL
 		MOV 	AH,09H
		LEA 	DX,MESSAGE1
 		INT 	21H
 		LEA 	SI, ASCIIREMAINDER
 		MOV 	AL, DH
		XLAT
 		MOV 	[SI], AL
 		MOV 	AH,09H
 		LEA 	DX, MESSAGE2
		INT 	21H
QUIT: 		MOV 	AL,0
 		MOV 	AH,04CH
		INT 	21H
 		CODE 	ENDS
		END 	START