CR EQU 0DH  
LF EQU 0AH  
DATA  SEGMENT   
TABLE DB '0123456789ABCDEF'  
MESSAGE DB ' THIS PROGRAM IS USED TO FIND THE SIZE OF THE RAM MEMORY IN KBYTES' 
 
 DB ' MEMORY SIZE IS RETURNED IN AX REGISTER' 
 
 DB CR,LF, '$'  
MEMORYSIZE DW ?  
DISPLAYSIZE DB ' THE RAM  MEMORY SIZE IS:'   
ASCIISIZE DB 4 DUP(?)  
 DB CR,LF,'$'  
DATA ENDS   
CODE SEGMENT   
 ASSUME CS:CODE, DS:DATA  
START: MOV AX, DATA  
 MOV DS,AX  
 MOV AH,09H  
 LEA DX,MESSAGE  
 INT 21H  
 MOV AH,088H  
 INT 15H  
 MOV MEMORYSIZE, AX 
LEA SI, ASCIISIZE  
 ADD SI,3  
 LEA BX, TABLE  
 MOV AX, MEMORYSIZE  
 AND AX,0000FH  
 XLAT   
 MOV [SI],AL  
 DEC SI  
 MOV AX, MEMORYSIZE  
 AND AX,000F0H  
 MOV CL,04H  
 SHR AX,CL  
 XLAT   
 MOV [SI],AL  
 DEC SI  
 MOV AX, MEMORYSIZE  
 AND AX,00F00H  
 MOV CL,08H  
 SHR AX,CL  
 XLAT   
 MOV [SI],AL  
 DEC SI  
 MOV AX, MEMORYSIZE  
 AND AX,0F000H  
 
 MOV CL,0CH  
 SHR AX,CL  
 XLAT   
 MOV [SI],AL  
 MOV AH,09H  
 LEA DX, DISPLAYSIZE  
 INT 21H  
QUIT: MOV AL,0  
 MOV AH,04CH  
 INT 21H  
 CODE ENDS  
 END START